spring:
  aop:
    #使你的项目支持 cglib的aop
    proxy-target-class: true
  disconf:
    #disconf包扫描路径
    scan-package: com.zen.spring.boot.demo.disconf
    #不需要自动reload的配置文件
    un-reload-files: myserver.properties
    #需要自动reload的配置文件
    reload-files: autoconfig.properties,autoconfig2.properties,myserver_slave.properties,testJson.json,testXml2.xml
    #是否使用远程配置文件，true(默认)会从远程获取配置 false则直接获取本地配置
    enable-remote-conf: true
    #配置服务器的 HOST(必填)，用逗号分隔  127.0.0.1:8000,127.0.0.1:8000
    conf-server-host: 127.0.0.1
    #APP 请采用 产品线_服务名 格式
    app: disconf_demo
    #环境
    env: rd
    #版本, 请采用 X_X_X_X 格式,注意要用单引号，不然Springboot将会解析成1000
    version: '1_0_0_0'
    #忽略哪些分布式配置，用逗号分隔
    ignore:
    #调试模式。调试模式下，ZK超时或断开连接后不会重新连接（常用于client单步debug）。非调试模式下，ZK超时或断开连接会自动重新连接。
    debug: false
    #获取远程配置 重试次数，默认是3次
    conf-server-url-retry-times: 1
    #获取远程配置 重试时休眠时间，默认是5秒
    conf-server-url-retry-sleep-seconds: 1
    #用户定义的下载文件夹, 远程文件下载后会放在这里。注意，此文件夹必须有有权限，否则无法下载到这里
    user-define-download-dir: /app/spring-boot/disconf/disconf-spring-boot-starter-demo
    #下载的文件会被迁移到classpath根路径下，强烈建议将此选项置为 true(默认是true)
    enable-local-download-dir-in-class-path: false
#日志配置
logging:
  level:
    com.baidu.disconf: debug